name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          texlive_version: 2023
          args: -gg

      - name: Upload PDF file
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --exclude '.gitignore' --exclude '.latexmkrc' --exclude '*.aux' --exclude '*.fdb_latexmk' --exclude '*.fls' --exclude '*.log' --exclude '*.ltjruby' --exclude '*.out' --exclude '*.gz' --exclude '*.tex' --exclude '*.aux' --exclude '*.toc'
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
